services:
  hyperion:
    image: ghcr.io/tbringuier/hyperionng-dockerized:latest
    container_name: hyperion
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Paris
    volumes:
      - hyperion_config:/config
    # ports:
    #   - "8090:8090"   # Web UI / JSON API
    #   - "8092:8092"   # JSON API (WebSocket)
    #   - "19444:19444" # Protobuf
    #   - "19445:19445" # Flatbuffers
    # devices:
    #   - /dev/video0:/dev/video0  # V4L2 USB capture

volumes:
  hyperion_config:
